# Docker para produccion o stage
FROM gradle:6.4.1-jdk11

ENV RABBIT_URL host.docker.internal
ENV MONGO_URL host.docker.internal
ENV AUTH_SERVICE_URL http://host.docker.internal:3000

WORKDIR /app
RUN curl -L https://github.com/nmarsollier/ecommerce_order_java/tarball/master | tar xz --strip=1
RUN gradle build fatJar

# Puerto de Order Service
EXPOSE 3004

CMD java -jar ./build/libs/order_java-all.jar
